### ISSUE TITLE
`OtpErlangAtom(b'true')` should be equal to `True`

### ISSUE THREAD

**Issue by weaversam8** [okeuday/erlang_py#13]
When parsing ETF in Python, you may the encounter Erlang atoms `true` and `false`. By convention, Erlang uses these values for true and false for boolean operators.

If a user constructs an `OtpErlangAtom` with the value `b'true'`, it should pass an equality test when compared with a Python `bool` type. Currently, [this code](https://github.com/okeuday/erlang_py/blob/bff65287a11c14a11e1dcc53d928a6f9710a677f/erlang.py#L162-L163) produces the following error:
https://github.com/okeuday/erlang_py/blob/bff65287a11c14a11e1dcc53d928a6f9710a677f/erlang.py#L162-L163
```
'bool' object has no attribute 'binary'
```

**Comment by okeuday** [comment]
The `OtpErlangAtom(b'true')` object in Python is not equal to the `True` in Python, even though they both become `true` in Erlang/OTP when either is encoded in the External Term Format in Python and decoded in Erlang/OTP with `erlang:binary_to_term/1`.  The same is true when using `OtpErlangAtom(u'true')`.
